/**
 * ChaWork 壳层 UI 默认文案（简体中文）。
 * 工作区 `ui/labels.yaml` 中同路径键可覆盖；未配置时使用此处。
 *
 * 键名使用点分层，与 `labelAtPath` 一致（对应 YAML 嵌套）。
 */
export const BUILTIN_UI_LABELS: Record<string, string> = {
  "app.product_name": "ChaWork",
  "app.mode_label": "通用助手",
  "app.search_placeholder": "⌘K 搜索工作区、资料、待确认事项或会话",
  "app.sync_badge": "资料已同步",
  "app.skill_button": "Skill",
  "app.skill_tip":
    "管理技能。全局技能会出现在所有工作区；当前工作区技能只保存在这个工作区文件夹里，用来适配这个工作区的工作方式。",
  "app.settings_title": "设置",
  "app.notifications_title": "通知",

  "sidebar.workspace_section": "工作区",
  "sidebar.workspace_section_tip":
    "这里显示当前员工绑定的工作区文件夹。每个文件夹保存资料、技能和多个会话。",
  "sidebar.open_workspace": "打开/添加工作区…",
  "sidebar.open_workspace_short": "打开工作区",
  "sidebar.expand_workspace_rail": "展开工作区栏",
  "sidebar.collapse_workspace_rail": "折叠工作区栏",
  "sidebar.settings": "设置",

  "workspace.new_folder": "打开/添加工作区",
  "workspace.add_for_employee": "添加工作区文件夹…",
  "workspace.employee_empty": "该员工还没有工作区，点击下方添加。",
  "workspace.card.meta_prefix": "文件夹",
  "workspace.none_selected": "未选择工作区",
  "workspace.click_to_switch": "点击选择员工与工作区",
  "workspace.cascade.kicker": "工作区",
  "workspace.cascade.title": "选择员工与工作区",
  "workspace.cascade.description": "先选员工，再选该员工下的工作区文件夹，或添加新文件夹。",
  "workspace.cascade.employees": "员工",
  "workspace.cascade.workspaces": "工作区",
  "workspace.cascade.empty_workspaces": "该员工还没有工作区。点击右侧「新建」添加文件夹。",
  "workspace.cascade.bound_employee_prefix": "员工",
  "workspace.cascade.new_employee": "新建",
  "workspace.cascade.new_workspace": "新建",
  "workspace.cascade.loading_workspaces": "加载工作区…",
  "workspace.cascade.general_recommended_badge": "推荐 · 首次使用",

  "session.section": "会话",
  "session.new_title": "新建会话",
  "session.empty": "暂无会话",
  "session.actions": "会话操作",
  "session.close_menu": "关闭菜单",
  "session.rename": "重命名",
  "session.delete": "删除",
  "session.rename_title": "重命名会话",
  "session.rename_cancel": "取消",
  "session.rename_save": "保存",
  "session.delete_title": "删除会话",
  "session.delete_confirm": "确定删除「{{title}}」？此操作不可恢复。",
  "session.delete_cancel": "取消",
  "session.delete_confirm_btn": "删除",

  "chat.header.tip":
    "这里是当前工作区里的一个会话。同一个工作区可以有多个会话，它们共享资料和技能，但聊天记录彼此独立。",
  "chat.header.switch_session": "切换会话",
  "chat.header.new_session": "新建会话",
  "chat.header.pending_review": "{{n}} 项待确认",
  "chat.header.model_unconfigured": "模型未配置",
  "chat.header.workspace_config": "工作区配置",
  "chat.header.project_materials": "项目资料",
  "chat.header.index_ready": "资料已准备好",
  "chat.header.index_building": "资料索引构建中",
  "chat.header.index_error": "资料索引出错",
  "chat.header.index_stale": "资料待索引",
  "chat.session_info.pick_workspace": "选择工作区后，在此开始对话。",
  "chat.session_info.folder_only": "工作区文件夹：{{name}}",
  "chat.session_info.full":
    "工作区文件夹：{{wname}} · 当前会话：{{stitle}} · workspace path: {{path}}",
  "chat.session_default_title": "新会话",
  "chat.empty.pick_workspace":
    "当前还没有打开工作区。先用「通用员工」打开一个项目文件夹，就可以开始对话。",
  "chat.empty.open_workspace": "用通用员工打开文件夹…",
  "chat.empty.new_session":
    "已打开工作区，但还没有可用会话。请点击左侧「会话」旁的 ＋ 新建一条会话，然后再发送消息。",
  "chat.empty.create_session": "新建会话",
  "chat.empty.card_title": "开始之前",
  "chat.empty.card_title_idle": "暂无消息",

  "composer.section": "输入区",
  "composer.upload_title": "上传文件",
  "composer.placeholder": "问 ChaWork，或拖入文档（PDF / DOCX / TXT / MD / XLSX / CSV）...",
  "composer.tip":
    "在这里输入问题，也可以导入 PDF、DOCX、TXT、MD、XLSX 或 CSV。AI 给出的保存建议会先进入右下角待确认区，不会直接改资料。",
  "composer.send": "发送",
  "composer.cancel_turn": "停止",
  "composer.remove_attachment": "移除图片",
  "composer.notice.dismiss": "关闭提示",
  "composer.send_blocked_no_workspace": "请先打开或选择一个工作区",
  "composer.send_blocked_loading": "正在同步工作区或会话，请稍候",
  "composer.send_blocked_no_session": "请在左侧「新建会话」或点选一条会话后再发送",
  "composer.send_blocked_open_workspace": "打开工作区",
  "composer.send_blocked_configure": "去配置",
  "composer.send_blocked_binding_check": "正在检查员工绑定状态，请稍候",
  "composer.send_blocked_no_employee": "此工作区尚未绑定员工，请先在下方完成绑定后再发送消息",
  "composer.send_blocked_workspace_runtime_busy": "当前工作区已有会话正在运行，请等待完成后再发送",
  "composer.send_blocked_streaming": "正在等待 AI 回复，请等待完成或点击停止",
  "composer.send_blocked_provider": "还没配置 AI 模型，完成后就可以开始聊天啦",

  "runtime.title": "AI 执行过程",
  "runtime.status_running": "运行中…",
  "runtime.status_idle": "就绪 · 暂无运行事件",
  "runtime.summary.title": "执行摘要",
  "runtime.summary.status_error": "错误",
  "runtime.summary.status_idle": "空闲",
  "runtime.summary.status_pending": "待确认",
  "runtime.summary.status_running": "运行中",
  "runtime.summary.open_details": "打开 Runtime 详情",
  "runtime.summary.close_details": "关闭",
  "runtime.summary.expand_panel": "展开 Runtime 面板",
  "runtime.summary.tool.generic": "工具",
  "runtime.summary.tool.search": "搜索",
  "runtime.summary.tool.search_knowledge": "知识检索",
  "runtime.summary.tool.read": "读取",
  "runtime.summary.tool.write": "写入",
  "runtime.summary.tool.edit": "编辑",
  "runtime.summary.tool.command": "命令",
  "runtime.summary.tool.list_dir": "列目录",
  "runtime.summary.tool.glob": "匹配文件",
  "runtime.summary.tool_call": "调用 · {{tool}}",
  "runtime.summary.file_changed": "变更",
  "runtime.summary.file_change": "{{action}} · {{path}}",
  "runtime.summary.retrieval": "检索 · {{query}}",
  "runtime.summary.plan": "计划 · {{summary}}",
  "runtime.summary.plan_update": "更新计划",
  "runtime.summary.executing": "执行中",
  "runtime.summary.results_count": "{{n}} 条结果",
  "runtime.companion.status_error": "需要处理",
  "runtime.companion.status_idle": "待命",
  "runtime.companion.status_pending": "等你确认",
  "runtime.companion.status_cancelling": "收尾中",
  "runtime.companion.status_thinking": "思考中",
  "runtime.companion.status_executing": "专注中",
  "runtime.filter.all": "全部",
  "runtime.filter.tool": "工具",
  "runtime.filter.file": "文件",
  "runtime.filter.mcp": "MCP",
  "runtime.filter.system": "系统",
  "runtime.inspector_tip":
    "这里显示 AI 正在做什么：读取资料、搜索、调用工具、整理候选更新。它只用于观察过程，不在这里确认保存。",
  "runtime.no_events": "暂无运行事件",
  "runtime.no_events_in_filter": "当前分类下无事件",

  "events.thinking.prefix": "思考 · {{summary}}",
  "events.thinking.title": "思考",
  "chat.thinking.title": "思考过程",
  "chat.thinking.done": "已完成",
  "chat.thinking.streaming": "思考中…",
  "chat.thinking.expand": "展开",
  "chat.empty_reply":
    "模型只完成了思考，未生成正文回复。请重试，或换一种问法。",
  "events.tool.prefix": "工具 · {{tool}}",
  "events.tool_delta.prefix": "工具输出 · {{tool}}",
  "events.tool_result.ok": "工具结果 · {{id}}",
  "events.tool_result.fail": "工具结果（失败） · {{id}}",
  "events.file.create": "新建",
  "events.file.modify": "修改",
  "events.file.delete": "删除",
  "events.file_change.label": "{{action}}文件 · {{path}}",
  "events.file_change_delta.title": "文件变更输出",
  "events.file_change_delta.output": "输出",
  "events.retrieval.label": "检索 · {{query}}（{{n}} 条）",
  "events.retrieval.badge": "知识检索",
  "events.retrieval.heading": "搜索查询",
  "events.retrieval.query_label": "查询: ",
  "events.retrieval.more": "… 还有 {{n}} 条结果",
  "events.mcp_oauth.completed": "MCP OAuth 完成 · {{server}}",
  "events.mcp_oauth.failed": "MCP OAuth 失败 · {{server}}",
  "events.mcp_oauth.badge_ok": "OAuth 完成",
  "events.mcp_oauth.badge_fail": "OAuth 失败",
  "events.mcp_server_status": "MCP 服务 · {{server}} · {{status}}",
  "events.plan_delta.title": "计划生成中",
  "events.plan_delta.body_label": "计划片段",
  "events.plan_done.title": "计划完成",
  "events.plan_done.body_label": "计划",
  "events.skill_write.badge": "Skill 写入",
  "events.skill_refresh.title": "Runtime 刷新",
  "events.skill_refresh.badge": "Runtime 刷新",
  "events.turn_complete.title": "本轮完成",
  "events.cancelled.title": "已取消",
  "events.badge.tool_args": "参数",
  "events.badge.tool_result": "结果",
  "events.badge.tool_error": "错误",
  "events.badge.file_diff": "差异",
  "review.diff_badge": "差异",
  "events.error.recoverable": "遇到问题，正在重试...",
  "events.error.fatal": "出现错误",

  "review.title": "待确认",
  "review.count_badge": "{{n}} 项",
  "review.empty": "暂无待确认事项",
  "review.history": "历史",
  "review.tip":
    "所有需要你审核的事情都排在这里。确认后才会保存到当前工作区；拒绝或编辑都不会影响原始资料。",
  "review.action.reject": "拒绝",
  "review.action.edit": "编辑",
  "review.action.accept": "确认",
  "review.keyboard.hint_allow_once": "Enter 本次允许 · Esc 拒绝",

  "review.risk.low": "低",
  "review.risk.medium": "中",
  "review.risk.high": "高",

  "review.status.accepted": "已确认",
  "review.status.rejected": "已拒绝",

  "message.source_copy": "复制路径",

  "import.title": "导入资料",
  "import.close": "关闭",
  "import.drop_hint": "拖拽文件到这里，或",
  "import.choose_file": "选择文件",
  "import.formats_hint": "支持 PDF · DOCX · TXT · MD · XLSX · CSV",
  "import.importing": "正在导入和解析…",
  "import.success_prefix": "导入成功：",
  "import.failure_prefix": "导入失败：",
  "import.error_unknown": "未知错误",
  "import.history_title": "最近导入",
  "import.dialog.supported_files": "支持的文件",
  "import.type.text": "文本",
  "import.type.markdown": "Markdown",
  "import.type.pdf": "PDF",
  "import.type.docx": "DOCX",
  "import.type.audio": "录音",
  "import.type.image": "图片",
  "import.type.unknown": "文件",
  "import.history.empty": "暂无导入记录",
  "import.history.wiki_badge": "已生成 wiki",
  "import.recorder.start_title": "开始录音",
  "import.recorder.stop_hint": "{{time}} · 点击停止",

  "knowledge.title": "知识库",
  "knowledge.project_materials": "项目资料",
  "knowledge.workspace_kicker": "工作区",
  "knowledge.project_materials_description": "导入资料、刷新索引、搜索并查看已入库文档",
  "knowledge.close_project_materials": "关闭项目资料",
  "knowledge.import_materials": "导入资料",
  "knowledge.drop_or_choose": "拖入文件，或选择本地文档",
  "knowledge.import_running": "有导入任务正在运行",
  "knowledge.import_tasks": "导入任务",
  "knowledge.search_materials": "搜索资料",
  "knowledge.close": "关闭",
  "knowledge.search_placeholder": "搜索知识库…",
  "knowledge.search_busy": "搜索中…",
  "knowledge.search_button": "搜索",
  "knowledge.results_empty": "暂无搜索结果",
  "knowledge.index.none": "索引未初始化",
  "knowledge.index.ready": "索引就绪",
  "knowledge.index.stale": "索引待构建",
  "knowledge.index.building": "索引构建中",
  "knowledge.index.error": "索引出错",
  "knowledge.index.legacy_busy": "索引处理中",
  "knowledge.refresh": "刷新",
  "knowledge.viewer.close": "关闭",
  "knowledge.viewer.loading": "加载中…",

  "settings.title": "设置",
  "settings.close": "关闭",
  "settings.tab.domain": "Domain Pack",
  "settings.tab.runtime": "Runtime",
  "settings.tab.workspace": "工作区",
  "settings.domain.title": "当前 Domain Pack",
  "settings.domain.loading": "加载中…",
  "settings.domain.reload": "重新加载",
  "settings.field.id": "ID",
  "settings.field.name": "名称",
  "settings.field.path": "路径",
  "settings.field.description": "描述",
  "settings.field.default_object_type": "默认对象类型",
  "settings.domain.templates_heading": "模板 ({{n}})",
  "settings.domain.skills_heading": "技能 ({{n}})",
  "settings.domain.workflows_heading": "工作流",
  "settings.domain.empty": "当前工作区未配置 Domain Pack",
  "settings.runtime.title": "Codex Runtime",
  "settings.field.status": "状态",
  "settings.field.model": "模型",
  "settings.runtime.model_hint": "见 .chawork/runtime/provider.json",
  "settings.runtime.model_howto":
    "推荐在「设置 · Provider」中填写 Base URL 和 API Key，自动获取模型列表后选择模型。完整路径：{{path}}",
  "settings.runtime.model_howto_no_workspace":
    "请先打开一个工作区，然后在「设置 · Provider」中填写 Base URL 和 API Key，并从自动获取的列表中选择模型。",
  "settings.runtime.reveal_provider": "打开 provider.json 所在位置",
  "settings.runtime.model_field_label": "模型",
  "settings.runtime.model_placeholder": "选择已获取的模型",
  "settings.runtime.model_gui_help":
    "保存后写入 `.chawork/runtime/provider.json`。若引导弹窗仍出现，可点「重新检测」或切换一次工作区。",
  "settings.runtime.model_save": "保存模型配置",
  "settings.runtime.model_saving": "保存中…",
  "settings.runtime.model_saved": "已保存",
  "settings.runtime.model_save_failed": "保存失败，请重试",
  "settings.runtime.instructions_field_label": "工作区系统指令",
  "settings.runtime.instructions_placeholder":
    "可选。保存后写入 provider.json 的 instructions，并通过 runtime 准备的 CODEX_HOME 生效；不会拼接进用户消息正文。",
  "settings.runtime.instructions_gui_help":
    "留空并保存可删除该字段。与 Domain Pack / AGENTS.md 可同时存在；二者会共同影响模型行为。",
  "settings.runtime.instructions_save": "保存系统指令",
  "settings.runtime.instructions_saving": "保存指令中…",
  "settings.runtime.instructions_saved": "指令已保存",
  "settings.runtime.instructions_save_failed": "保存失败，请重试",
  "settings.runtime.connection_heading": "OpenAI 连接（可选）",
  "settings.runtime.openai_base_url_label": "API Base URL",
  "settings.runtime.openai_base_url_placeholder":
    "例如 https://api.openai.com/v1 或自建代理地址",
  "settings.runtime.openai_api_key_label": "API Key",
  "settings.runtime.openai_api_key_placeholder":
    "留空表示不在本机 provider.json 中保存密钥",
  "settings.runtime.connection_gui_help":
    "Base URL 会写入 Codex 的 config.toml（托管 OpenAI-compatible provider）。Key 保存在全局 provider.json，并在启动 Runtime 时注入为环境变量 OPENAI_API_KEY。请勿将含密钥的文件提交到公开仓库。",
  "settings.runtime.connection_save": "保存连接配置",
  "settings.runtime.connection_saving": "保存连接中…",
  "settings.runtime.connection_saved": "连接已保存",
  "settings.runtime.connection_save_failed": "保存失败，请重试",
  "settings.runtime.prompt_hint":
    "每条对话的「用户消息」仍在底部输入框发送。上方系统指令适合放长期约束；更长的领域说明也可在 Domain Pack 的 `AGENTS.md` 中维护。",
  "settings.runtime.mcp_qmd": "qmd_knowledge — 知识检索",

  "onboarding.provider.title": "开始使用前",
  "onboarding.provider.lead":
    "当前工作区尚未配置可用模型。每次启动都会显示本提示，直到在「设置 · Provider」中保存 Base URL、API Key 和已选择的模型。",
  "onboarding.provider.step_model": "1. 配置模型",
  "onboarding.provider.step_model_detail":
    "推荐：点「打开设置 · Provider」，填写 Base URL 和 API Key，自动获取模型列表后选择模型。",
  "onboarding.provider.step_prompt": "2. 发送首条对话",
  "onboarding.provider.step_prompt_detail":
    "在底部输入区编写你的问题或任务说明；左侧需已选中或新建会话后再点「发送」。这与模型配置相互独立。",
  "onboarding.provider.reveal": "打开 provider.json 所在位置",
  "onboarding.provider.open_runtime": "打开设置 · Runtime",
  "onboarding.provider.recheck": "重新检测",
  "onboarding.provider.later": "稍后继续",
  "onboarding.tour.provider.title": "先配置 AI 模型",
  "onboarding.tour.provider.body":
    "ChaWork 需要一个可用的模型 Provider 才能对话。先从设置里填写 Base URL、API Key 并选择模型。",
  "onboarding.tour.provider.action": "去配置",
  "onboarding.tour.workspace.title": "先打开项目文件夹",
  "onboarding.tour.workspace.body":
    "ChaWork 围绕工作区协作。第一次打开文件夹时，会默认帮你使用通用员工。",
  "onboarding.tour.workspace.action": "打开工作区",
  "onboarding.tour.binding.title": "绑定通用员工",
  "onboarding.tour.binding.body":
    "新手可以直接使用通用员工。绑定后，这个工作区就能使用员工 prompt 和 skills。",
  "onboarding.tour.session.title": "会话保存在工作区里",
  "onboarding.tour.session.body":
    "同一个工作区可以有多条会话。每条会话共享项目资料，但聊天记录彼此独立。",
  "onboarding.tour.dream.title": "认识 Dream 学习闭环",
  "onboarding.tour.dream.body":
    "完成几次真实任务后，可在员工的 Dream 标签页触发分析。Dream 会提议 prompt 更新，你在 Review Queue 中批准后才生效。",
  "onboarding.tour.dream.action": "打开 Dream",
  "onboarding.tour.skip": "跳过",
  "onboarding.tour.previous": "上一步",
  "onboarding.tour.next": "下一步",
  "onboarding.tour.done": "完成",
  "onboarding.tour.skip_aria": "跳过引导",
  "onboarding.tour.reopen": "重新打开新手引导",
  "onboarding.tour.settings_title": "新手引导",
  "onboarding.tour.settings_description": "重新查看首次使用的工作区与员工绑定引导。",
  "onboarding.tour.target_missing_hint":
    "完成前面的步骤后，这个位置会出现在界面中。你也可以继续查看下一步。",
  "onboarding.binding.use_general": "使用通用员工",
  "onboarding.binding.other_employee": "绑定到其他员工",
  "onboarding.binding.create_employee": "创建员工并绑定",
  "settings.runtime.mcp_heading": "MCP Servers",
  "settings.runtime.mcp_workspace": "chawork_workspace — 文件读写与内嵌 search_knowledge（BM25）",
  "settings.workspace.title": "工作区信息",
  "settings.workspace.no_workspace": "未选择工作区",
  "settings.workspace.qmd_heading": "QMD 索引",
  "settings.workspace.qmd_ready": "就绪",
  "settings.workspace.qmd_not_ready": "未就绪",
  "settings.workspace.refresh_index": "刷新索引",
  "settings.workspace.dir_layout": "目录结构",

  "locale.option.zh": "简体中文",
  "locale.option.en": "English",
  "locale.section.title": "语言",
  "locale.section.description": "切换界面显示语言。默认使用简体中文。",
  "theme.section.title": "外观",
  "theme.section.description": "切换全局界面风格。深色风格参考 VS Code Dark+。",
  "theme.option.light": "浅色",
  "theme.option.vscode_dark": "VS Code 深色",

  "global_settings.title": "全局设置",
  "global_settings.description": "配置全局 Provider、根工作区、Dream 与界面语言",
  "global_settings.close": "关闭",
  "global_settings.tab.general": "通用",
  "global_settings.tab.root_runtime": "根 Runtime",
  "global_settings.tab.provider": "模型 Provider",
  "global_settings.tab.dream": "Dream",
  "global_settings.tab.global_skills": "全局 Skills / MCP",
  "global_settings.tab.templates": "全局模板",
  "global_settings.root_runtime.title": "根工作区 Runtime",
  "global_settings.field.path": "路径",
  "global_settings.field.codex_home": "Codex Home",
  "global_settings.loading": "加载中…",
  "global_settings.runtime.check": "检查 Runtime",
  "global_settings.runtime.checking": "检查中…",
  "global_settings.provider.title": "全局模型配置",
  "global_settings.provider.configured": "已配置",
  "global_settings.provider.not_configured": "未配置",
  "global_settings.provider.config_file": "全局配置文件",
  "global_settings.provider.model": "模型",
  "global_settings.provider.model_placeholder": "选择模型",
  "global_settings.provider.models_loading": "正在获取模型列表…",
  "global_settings.provider.model_waiting": "先填写 Base URL 和 API Key",
  "global_settings.provider.base_url": "Base URL",
  "global_settings.provider.api_key": "API Key",
  "global_settings.provider.api_key_saved_hint": "已保存 {{masked}}，留空表示不修改",
  "global_settings.provider.api_key_empty_hint": "留空表示不在 provider.json 中保存密钥",
  "global_settings.provider.instructions": "Instructions",
  "global_settings.provider.save": "保存全局模型",
  "global_settings.provider.saving": "保存中…",
  "global_settings.provider.reveal": "打开全局 provider.json",
  "global_settings.dream.title": "Dream 全局配置",
  "global_settings.dream.default_time": "默认触发时间",
  "global_settings.dream.default_time_hint":
    "每日定时调度模式下，如果员工未单独配置触发时间，将使用此全局默认时间。",
  "global_settings.dream.save": "保存",
  "global_settings.dream.saving": "保存中…",
  "global_settings.dream.current_default": "当前全局默认：{{time}}",
  "global_settings.dream.per_employee_hint":
    "每位员工可以在自己的 Dream 配置中覆盖此时间。未设置覆盖的员工将使用此全局默认值。",
  "global_settings.skills.title": "全局 Skill 目录",
  "global_settings.skills.mcp_dir": "MCP 目录",
  "global_settings.skills.loading": "加载技能目录…",
  "global_settings.skills.empty": "暂无全局 Skill",
  "global_settings.templates.empty": "模板管理暂未实现",

  "employee.panel.title": "员工管理",
  "employee.panel.open_with_badge": "员工管理",
  "employee.review.badge_pending": "有待审批的 Dream 更新",
  "employee.context.none_selected": "未选择员工",
  "employee.context.empty": "暂无普通员工，请先在员工管理中创建。",
  "employee.panel.description": "管理员工 Prompt、Skills、Dream 与工作区绑定",
  "employee.panel.close": "关闭",
  "employee.list.title": "员工列表",
  "employee.list.empty": "暂无员工",
  "employee.list.create_hint": "点击左上角 + 创建第一个员工",
  "employee.list.select_hint": "选择左侧员工查看详情",
  "employee.list.create_employee": "创建员工",
  "employee.tab.overview": "概览",
  "employee.tab.workspaces": "工作区",
  "employee.tab.prompt": "Prompt",
  "employee.tab.skills": "Skills",
  "employee.tab.dream": "Dream / 审批",
  "employee.tab.review_queue": "审批队列",
  "employee.kind.dream": "Dream 员工",
  "employee.kind.ordinary": "普通员工",
  "employee.dream.ordinary_only": "Dream 仅适用于普通员工",
  "employee.dream.loading": "加载 Dream 状态...",
  "employee.review.loading": "加载审批队列...",
  "employee.dream.config_title": "Dream 配置",
  "employee.dream.enable_title": "启用 Dream",
  "employee.dream.enable_hint": "开启后该员工将参与 Dream prompt 改进流程",
  "employee.dream.schedule_type": "调度方式",
  "employee.dream.schedule_manual": "手动触发",
  "employee.dream.schedule_daily": "每日定时",
  "employee.dream.schedule_manual_hint": "通过下方「运行 Dream」入口手动触发。",
  "employee.dream.trigger_time": "触发时间",
  "employee.dream.global_default_badge": "全局默认 {{time}}",
  "employee.dream.restore_global_default": "恢复全局默认",
  "employee.dream.daily_at_time": "该员工将在每日 {{time}} 自动触发 Dream",
  "employee.dream.daily_use_global":
    "使用全局默认时间 {{time}}，可在全局设置 → Dream 中修改",
  "employee.dream.session_scan": "会话扫描范围",
  "employee.dream.scan_all": "全部工作区",
  "employee.dream.scan_selected": "指定工作区",
  "employee.dream.scan_selected_hint":
    "指定工作区功能将在后续版本中提供可视化选择器。当前通过 dream.yaml 手动配置 workspace_subset。",
  "employee.dream.run_title": "运行 Dream",
  "employee.dream.run_hint": "Dream 会分析该员工最近的会话记录，生成 prompt 改进建议。",
  "employee.dream.run_button": "运行 Dream",
  "employee.dream.running": "Dream 运行中...",
  "employee.dream.cancel": "取消",
  "employee.dream.output_live": "Dream 输出（实时）",
  "employee.dream.output_done": "Dream 执行输出",
  "employee.dream.waiting_codex": "等待 Codex 响应...",
  "employee.dream.error_title": "Dream 执行出错",
  "employee.overview.manual_dream_title": "手动测试 Dream",
  "employee.overview.manual_dream_hint":
    "立即分析最近会话，生成待审批的 prompt 更新建议。",
  "employee.overview.manual_dream_button": "运行 Dream",
  "employee.overview.manual_dream_running": "Dream 运行中...",
  "employee.dream.recent_title": "最近 Dream 结果",
  "employee.dream.result_parse_failed": "解析失败",
  "employee.dream.result_update_required": "建议更新",
  "employee.dream.result_no_update": "无需更新",
  "employee.dream.sessions_analyzed": "基于 {{count}} 个会话分析",
  "employee.dream.view_raw_output": "查看原始输出",
  "employee.dream.logs_toggle": "运行日志",
  "employee.review.applying": "正在应用 prompt 更新...",
  "employee.review.success": "Prompt 更新成功",
  "employee.review.failed": "Prompt 更新失败",
  "employee.review.confirm_ok": "确定",
  "employee.review.empty": "暂无待审批的 prompt 更新请求",
  "employee.review.pending_title": "待审批更新",
  "employee.review.dream_run_meta": "Dream 运行: {{runId}} · {{createdAt}}",
  "employee.review.target_path": "目标: {{path}}",
  "employee.review.summary": "摘要",
  "employee.review.impact": "影响范围: {{impact}}",
  "employee.review.source_sessions": "基于会话",
  "employee.review.updates_heading": "更新内容 ({{count}} 条)",
  "employee.review.reason": "原因: {{reason}}",
  "employee.review.action.add": "新增",
  "employee.review.action.modify": "修改",
  "employee.review.action.remove": "删除",
  "employee.review.status.pending": "待审批",
  "employee.review.status.approved": "已批准",
  "employee.review.status.applying": "应用中",
  "employee.review.status.applied": "已应用",
  "employee.review.status.rejected": "已拒绝",
  "employee.review.status.failed": "失败",
  "employee.review.approve": "批准并应用",
  "employee.review.reject": "拒绝",
  "employee.review.confirm_approve":
    "确认批准此 prompt 更新？批准后将立即应用到员工 prompt。",
  "employee.review.confirm_reject": "确认拒绝此更新请求？",
  "employee.logs.title": "Dream 运行日志",
  "employee.logs.refresh": "刷新日志",
  "employee.logs.loading": "加载中…",
  "employee.logs.empty": "暂无日志记录",

  "employee.overview.no_manifest": "未找到员工 manifest 数据",
  "employee.overview.basic_info": "基本信息",
  "employee.overview.edit": "编辑",
  "employee.overview.field.name": "名称",
  "employee.overview.field.description": "描述",
  "employee.overview.field.kind": "类型",
  "employee.overview.field.status": "状态",
  "employee.overview.field.created_at": "创建时间",
  "employee.overview.field.updated_at": "更新时间",
  "employee.overview.save": "保存",
  "employee.overview.cancel": "取消",
  "employee.overview.integrity": "完整性检查",
  "employee.overview.integrity_ok": "完整性正常",
  "employee.overview.integrity_fix": "需要修复",
  "employee.overview.recent_dream": "最近 Dream 结果",
  "employee.overview.workspaces_hint":
    "这些工作区会使用当前员工的 Prompt 和 Skills。",

  "employee.prompt.title": "Prompt",
  "employee.prompt.loading": "正在加载 Prompt...",
  "employee.prompt.empty":
    "Prompt 为空。可点击「编辑」直接填写 prompt.md。",
  "employee.prompt.edit_hint": "支持 Markdown 预览，也可以直接编辑 prompt.md。",
  "employee.prompt.edit": "编辑",
  "employee.prompt.save": "保存",
  "employee.prompt.cancel": "取消",
  "employee.prompt.show_source": "源码",
  "employee.prompt.show_preview": "预览",

  "employee.skills.title": "员工 Skills ({{count}})",
  "employee.skills.copy_from_root": "添加 Skill",
  "employee.skills.picker_title": "从 Root 添加 Skill",
  "employee.skills.copy_action": "添加",
  "employee.skills.source_root": "Root",
  "employee.skills.no_description": "无描述",
  "employee.skills.status_enabled": "已启用",
  "employee.skills.status_disabled": "已禁用",
  "employee.skills.close": "关闭",
  "employee.skills.search_placeholder": "搜索 skill…",
  "employee.skills.no_copyable": "无可复制的 Skill",
  "employee.skills.empty": "暂无 Skill，点击上方按钮添加",
  "employee.skills.enable": "启用",
  "employee.skills.disable": "禁用",
  "employee.skills.delete": "删除",
  "employee.skills.copied_from": "copied from {{id}}",
  "employee.skills.confirm_delete":
    "确定删除员工内的 Skill「{{id}}」快照？Root skills 中的原始技能不会被删除。",

  "employee.workspaces.bound_title": "已绑定工作区",
  "employee.workspaces.add_workspace": "添加工作区",
  "employee.workspaces.empty_hint":
    "该员工还没有专属工作区。点击「添加工作区」选择或新建文件夹。",
  "employee.workspaces.bind": "绑定工作区",
  "employee.workspaces.picker_title": "选择要绑定的工作区",
  "employee.workspaces.close": "关闭",
  "employee.workspaces.search_placeholder": "搜索工作区…",
  "employee.workspaces.no_available": "无可绑定的工作区",
  "employee.workspaces.bind_this": "绑定此工作区",
  "employee.workspaces.empty": "暂未绑定任何工作区",
  "employee.workspaces.bound_at": "绑定于 {{time}}",
  "employee.workspaces.unbind": "解绑此工作区",
  "employee.workspaces.confirm_unbind":
    "确定解绑工作区「{{name}}」？解绑后此工作区将不再使用当前员工的 Prompt 和 Skills。",

  "employee.create.title": "创建员工",
  "employee.create.description": "设置员工名称、初始 Prompt，并可从 Root 复制 Skills；员工 ID 由系统自动生成。",
  "employee.create.field.name": "名称",
  "employee.create.name_placeholder": "例如：前端开发助手",
  "employee.create.field.id": "ID",
  "employee.create.id_placeholder": "auto-generated-from-name",
  "employee.create.id_hint": "仅允许小写字母、数字和连字符（kebab-case），自动从名称生成",
  "employee.create.id_invalid": "ID 格式无效，仅允许 a-z、0-9 和 -（不能以 - 开头或结尾）",
  "employee.create.field.description": "描述（可选）",
  "employee.create.description_placeholder": "这个员工的职责和能力…",
  "employee.create.field.initial_prompt": "初始 Prompt（可选）",
  "employee.create.prompt_placeholder": "员工默认系统 Prompt…",
  "employee.create.field.root_skills": "从 Root 复制 Skills（可选）",
  "employee.create.no_root_skills": "暂无 Root Skill 可复制，创建后可在员工详情中添加",
  "employee.create.cancel": "取消",
  "employee.create.submit": "创建",
  "employee.create.submitting": "创建中…",
}

/** Replace `{{key}}` placeholders in a label string. */
export function applyLabelTemplate(
  template: string,
  vars: Record<string, string>,
): string {
  let s = template
  for (const [k, v] of Object.entries(vars)) {
    s = s.split(`{{${k}}}`).join(v)
  }
  return s
}
